name: 'test varaible export'

on:
  push:
    branches:
      - "master"

jobs:
  variable_export:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: set variable output
        id: dev_vars
        run: | 
          export PROJECT_ID='DEVOPS'
          echo "::set-output name=PROJECT_ID::$PROJECT_ID"
        if: github.ref == 'refs/heads/master'

      - name: print output
        run: ${{ steps.vars.outputs.PROJECT_ID }}