name: 'test varaible export'

on:
  push:
    branches:
      - "master"
      - "dev"

jobs:
  variable_export:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/
          mode: stage
        if: github.ref == 'refs/heads/master'

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/
          mode: development
        if: github.ref == 'refs/heads/dev' 

      - name: set variable output
        run: |
          echo "${{ env.PROJECT_ID }}"


