name: workflow

on:
  push:
    branches:
      - "master"

jobs:
  nonprod_variable_export:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      # - name: Load .env file
      #   uses: xom9ikk/dotenv@v1.0.2
      #   with:
      #     path: .github/workflows/
      #     mode: stage
      #   if: github.ref == 'refs/heads/master'

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/
          mode: development
        if: github.ref == 'refs/heads/dev' 

      # - name: Load .env file
      #   uses: xom9ikk/dotenv@v1.0.2
      #   with:
      #     path: .github/workflows/
      #     mode: prod

      - name: set variable output
        run: |
            echo ${{ env.environment }}
            echo ${{ env.project_id }}

  prod_variable_export:
    strategy:
      matrix:
        project_id: [production1, production2, production3]
    runs-on: ubuntu-latest
    steps:
      # - name: Load .env file
      #   uses: xom9ikk/dotenv@v1.0.2
      #   with:
      #     path: .github/workflows/
      #     mode: prod
      #   if: github.ref == 'refs/heads/master'

      - name: print 
        run: | 
          echo "${{ github.run_id }}"
          echo "${{ matrix.project_id }}:${{ github.run_id }}"
