name: server_restart
on:
  repository_dispatch:
    types: [trigger-repo]

jobs:
  repo_dispatch_trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch name
        id: vars
        run: |
          result=${{ toJson(github.event.client_payload.branch_name) }}
          $echo "BRANCH=$result" >> $GITHUB_OUTPUT

      - name: get branch name
        run: echo ${{ steps.vars.outputs.BRANCH }}
