name: server_restart
on:
  repository_dispatch:
    types: [trigger-repo]

jobs:
  repo_dispatch_trigger:
    runs-on: ubuntu-latest
    steps:
      
      - name: Set branch name
        id: vars
        run: |
          echo "branch=${{ toJson(github.event.client_payload.branch_name) }}
          #echo "BRANCH=$branch" >> $GITHUB_ENV

      - name: get branch name
        run: |
          echo $branch
        env:
          branch: ${{ steps.vars.outputs.BRANCH }}